/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula_19_de_agosto;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class Buscar extends javax.swing.JFrame {

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jTextFieldBusca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxBusca = new javax.swing.JComboBox();
        jButtonBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite a sua busca:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Busca");

        jComboBoxBusca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FunCod", "FunNome", "FunRg", "FunCpf", "TelRes", "TelCel", "TelCod", "EndCod", "EndLog", "EndNum", "EndCom", "EndBai", "EndCid", "EndCep", "EndEst" }));
        jComboBoxBusca.setName(""); // NOI18N
        jComboBoxBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBuscaActionPerformed(evt);
            }
        });

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Selecione o tipo de busca:");

        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonVoltar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

        if (!jTextFieldBusca.getText().equals("")) {
            String BuscarCod;

            ResultSet ResultadoCompleto[] = new ResultSet[3];
            String BuscaCompleta[] = new String[3];
            Object TipoBusca = jComboBoxBusca.getSelectedItem();

            JOptionPane.showMessageDialog(null, TipoBusca);
            int TabelaBusca = jComboBoxBusca.getSelectedIndex();
            // Funcionario --> 0-3
            // Telefone -->4-6
            // Endereço --> >7

            if (TabelaBusca >= 0 && TabelaBusca <= 3) { //Buscar na tabela Funcionário
                if (TabelaBusca==0){
                BuscarCod = "SELECT FunCod FROM funcionario where " + TipoBusca + " = "
                        + jTextFieldBusca.getText();
                }else {  
                BuscarCod = "SELECT FunCod FROM funcionario where " + TipoBusca + " = '"
                        + jTextFieldBusca.getText() +"'";
                    
                }
            } else if (TabelaBusca >= 4 && TabelaBusca <= 6) {//Buscar na tabela Telefone
                if (TabelaBusca==6){
                     BuscarCod = "SELECT TelCod FROM telefone where " + TipoBusca + " = "
                        + jTextFieldBusca.getText();
                }else{
                        BuscarCod = "SELECT TelCod FROM telefone where " + TipoBusca + " = '"
                        + jTextFieldBusca.getText() +"'";
                }
                
            } else {// Buscar na tabela Endereço
               if (TabelaBusca==7){
                 BuscarCod = "SELECT EndCod FROM endereco where " + TipoBusca + " = "
                        + jTextFieldBusca.getText();
               }else{
                          BuscarCod = "SELECT EndCod FROM endereco where " + TipoBusca + " = '"
                        + jTextFieldBusca.getText() +"'";
               }
              
            }
            JOptionPane.showMessageDialog(null, BuscarCod);
            Conexao con = new Conexao();
            try {
                if (con.Conecta()) {
                    PreparedStatement consulta;
                    consulta = con.con.prepareStatement(BuscarCod);
                    ResultSet rs = consulta.executeQuery();

                    rs.next(); //Busca o 1º registro
                    ///resultadoBusca ... GetString

                    if (!rs.wasNull()) {//Se o resultado for nulo...
                        BuscaCompleta[0] = "SELECT * FROM funcionario WHERE FunCod=" + rs.getString(1);
                        BuscaCompleta[1] = "SELECT * FROM telefone WHERE TelCod=" + rs.getString(1);
                        BuscaCompleta[2] = "SELECT * FROM endereco WHERE EndCod=" + rs.getString(1);
                       
                         
                        for (int i = 0; i < 3; i++) {
                            
                            consulta = con.con.prepareStatement(BuscaCompleta[i]);
                            ResultadoCompleto[i] = consulta.executeQuery();
                            ResultadoCompleto[i].next();
                        }
                        
                        JOptionPane.showMessageDialog(null, ""
                                + "DADOS DO FUNCIONÁRIO"
                                + "\n======================================"
                                + "\nCódigo = " + ResultadoCompleto[0].getString("FunCod")
                                + "\nNome = "   + ResultadoCompleto[0].getString("FunNome")
                                + "\nRG ="      + ResultadoCompleto[0].getString("FunRg")
                                + "\nCPF="      + ResultadoCompleto[0].getString("FunCpf")
                                + "\n"
                                + "\nDADOS DO TELEFONE"
                                + "\n======================================"
//                                + "\nCódigo ="         + ResultadoCompleto[1].getString("TelCod")
                                + "\nResidencial ="    + ResultadoCompleto[1].getString("TelRes")
                                + "\nCelular ="        + ResultadoCompleto[1].getString("TelCel")
                                + "\n"
                                + "\nDADOS DO ENDERECO"
                                + "\n======================================"
                                + "\nCódigo ="         + ResultadoCompleto[2].getString("EndCod")
                                + "\nLogradouro ="     + ResultadoCompleto[2].getString("EndLog")
                                + "\nNúmero ="         + ResultadoCompleto[2].getString("EndNum")
                                + "\nComplemento ="    + ResultadoCompleto[2].getString("EndCom")
                                + "\nBairro ="         + ResultadoCompleto[2].getString("EndBai")
                                + "\nCidade ="         + ResultadoCompleto[2].getString("EndCid")
                                + "\nEstado ="         + ResultadoCompleto[2].getString("EndEst")
                                + "\nCEP ="            + ResultadoCompleto[2].getString("EndCEP")                        
                        );
                        
                       
                    } else {
                        JOptionPane.showMessageDialog(null, "Pesquisa Realizada\n"
                                + "Nenhum resultado foi encontrado");
                    }

                    con.Fechar();
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);
            }


    }//GEN-LAST:event_jButtonBuscarActionPerformed
 else {
            JOptionPane.showMessageDialog(null, "Campo de busca vazio.");
        }
    }

    private void jComboBoxBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox jComboBoxBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextFieldBusca;
    // End of variables declaration//GEN-END:variables
}
