/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.etec.CosmeticosTelas;

import br.com.etec.ConectionFactory.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kelvin
 */
public class BuscarFabricantes extends javax.swing.JFrame {

    /**
     * Creates new form BuscarFabricantes
     */
    public BuscarFabricantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jComboBoxCampoPesquisa = new javax.swing.JComboBox();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jToggleButtonPesquisar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFabricante = new javax.swing.JTable();
        jToggleButtonVoltar = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Buscar - Fabricantes");

        jComboBoxCampoPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FabNome", "FabCNPJ", "TelRes", "TelCel", "EndRua", "EndCid", "EndEst", " " }));

        jToggleButtonPesquisar.setText("Pesquisar");
        jToggleButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPesquisarActionPerformed(evt);
            }
        });

        jTableFabricante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fabricante", "CNPJ", "Residencial", "Celular", "Rua", "Cidade", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTableFabricante);

        jToggleButtonVoltar.setText("Voltar");
        jToggleButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonVoltarActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesquisar por:");

        jLabel2.setText("Pesquisa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel1)
                                .addGap(93, 93, 93)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jComboBoxCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(jToggleButtonPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButtonVoltar)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonPesquisar)))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButtonVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonVoltarActionPerformed
        Menu_Buscas buscas = new Menu_Buscas();
        buscas.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jToggleButtonVoltarActionPerformed

    private void jToggleButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPesquisarActionPerformed
        DefaultTableModel tabela;
        tabela = (DefaultTableModel) jTableFabricante.getModel();
        tabela.setRowCount(0);
        
        ArrayList<String> CodigosFabricantes = new ArrayList<>();
        
        PreparedStatement stm;
        ResultSet rs = null;
        
        Boolean DadosRetornados = true;
        Conexao conecta = new Conexao();
        
        int numeroTabela = jComboBoxCampoPesquisa.getSelectedIndex() + 1;
        
        String pesquisa = jTextFieldPesquisa.getText();
        
        String sql = null;
        
        switch (numeroTabela) {
            case 1:
                sql = "SELECT fabricante.FabNome, fabricante.FabCNPJ, telefone.TelRes, telefone.TelCel, endereco.EndRua, endereco.EndCid, endereco.EndEst FROM fabricante, telefone, endereco WHERE fabricante.FabNome = '"+pesquisa+"' AND FabTel = telefone.TelCod AND fabricante.FabEnd = endereco.EndCod";
                break;
            case 2:
                sql = "SELECT fabricante.FabNome, fabricante.FabCNPJ, telefone.TelRes, telefone.TelCel, endereco.EndRua, endereco.EndCid, endereco.EndEst FROM fabricante, telefone, endereco WHERE fabricante.FabCNPJ = "+pesquisa+" AND FabTel = telefone.TelCod AND fabricante.FabEnd = endereco.EndCod";
                break;
            case 3:
                sql = "SELECT fabricante.FabNome, fabricante.FabCNPJ, telefone.TelRes, telefone.TelCel, endereco.EndRua, endereco.EndCid, endereco.EndEst FROM fabricante, telefone, endereco WHERE telefone.TelRes = "+pesquisa+" AND FabTel = telefone.TelCod AND fabricante.FabEnd = endereco.EndCod";
                break;
            case 4:
                sql = "SELECT fabricante.FabNome, fabricante.FabCNPJ, telefone.TelRes, telefone.TelCel, endereco.EndRua, endereco.EndCid, endereco.EndEst FROM fabricante, telefone, endereco WHERE telefone.TelCel = "+pesquisa+" AND FabTel = telefone.TelCod AND fabricante.FabEnd = endereco.EndCod";
                break;
            case 5:  
                sql = "SELECT fabricante.FabNome, fabricante.FabCNPJ, telefone.TelRes, telefone.TelCel, endereco.EndRua, endereco.EndCid, endereco.EndEst FROM fabricante, telefone, endereco WHERE endereco.EndRua = '"+pesquisa+"' AND FabTel = telefone.TelCod AND fabricante.FabEnd = endereco.EndCod";
                break;
            case 6:
                sql = "SELECT fabricante.FabNome, fabricante.FabCNPJ, telefone.TelRes, telefone.TelCel, endereco.EndRua, endereco.EndCid, endereco.EndEst FROM fabricante, telefone, endereco WHERE endereco.EndCid = '"+pesquisa+"' AND FabTel = telefone.TelCod AND fabricante.FabEnd = endereco.EndCod";
                break;
            case 7:
                sql = "SELECT fabricante.FabNome, fabricante.FabCNPJ, telefone.TelRes, telefone.TelCel, endereco.EndRua, endereco.EndCid, endereco.EndEst FROM fabricante, telefone, endereco WHERE endereco.EndEst = '"+pesquisa+"' AND FabTel = telefone.TelCod AND fabricante.FabEnd = endereco.EndCod";
                break;
            default:
                sql = null;
        }
        
        if (DadosRetornados != false) {
            if (!pesquisa.equals("")) {
                if (conecta.getCon()) {
                    try {
                        stm = conecta.con.prepareStatement(sql);
                        rs = stm.executeQuery();
                        
                        while (rs.next()) {
  
                            tabela.addRow(new String[]{rs.getString("FabNome"), rs.getString("FabCNPJ"),
                            rs.getString("TelRes"), rs.getString("TelCel"), rs.getString("EndRua"),
                            rs.getString("EndCid"),rs.getString("EndEst")});
                        }
                        conecta.fechar();
                    } catch (SQLException err) {
                        System.out.println("Erro: " + err.getMessage());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Nenhum Resultado foi encontrado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                }
            } 
            }else {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
            
    }//GEN-LAST:event_jToggleButtonPesquisarActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarFabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarFabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarFabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarFabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarFabricantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxCampoPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFabricante;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JToggleButton jToggleButtonPesquisar;
    private javax.swing.JToggleButton jToggleButtonVoltar;
    // End of variables declaration//GEN-END:variables
}
