/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.etec.CosmeticosTelas;

import br.com.etec.ConectionFactory.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kelvin
 */
public class BuscarVendas extends javax.swing.JFrame {

    /**
     * Creates new form BuscarVendas
     */
    public BuscarVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxCampoPesquisa = new javax.swing.JComboBox();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVenda = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButtonPesquisar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Buscar - Vendas");

        jLabel1.setText("Procurar por:");

        jLabel2.setText("Pesquisa:");

        jComboBoxCampoPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VendCod", "VendQuant", "VendPreco", "VendProd", "VendFun", " " }));

        jTableVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Produto", "Quantidade", "Valor", "Funcionario"
            }
        ));
        jScrollPane1.setViewportView(jTableVenda);

        jToggleButton1.setText("Voltar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButtonPesquisar.setText("Pesquisar");
        jToggleButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel1)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jComboBoxCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel14)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        Menu_Buscas buscas = new Menu_Buscas();
        buscas.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPesquisarActionPerformed
        DefaultTableModel tabela;
        tabela = (DefaultTableModel) jTableVenda.getModel();
        tabela.setRowCount(0);

        ArrayList<String> CodigosVenda = new ArrayList<>();

        PreparedStatement stm;
        ResultSet rs = null;

        Boolean DadosRetornados = true;
        Conexao conecta = new Conexao();

        // String VendCod, ProNome, VendQuant, VendPreco, FunNome;
        //Fase 1
        int numeroTabela = jComboBoxCampoPesquisa.getSelectedIndex() + 1;

        //String campoPesquisa = jComboBoxCampoPesquisa.getSelectedItem().toString();
        String pesquisa = jTextFieldPesquisa.getText();

        //Fase 2
        String sql = null;

//        if (!pesquisa.equals("")) {
//            if (numeroTabela >= 1 && numeroTabela <= 3) {
//                sql = "select VendCod from vendas where " + campoPesquisa + " in ('" + pesquisa + "')";
//            } else if (numeroTabela == 4) {
//                sql = "SELECT VendCod FROM vendas WHERE VendProd IN (SELECT ProCod FROM Produto WHERE " + campoPesquisa + " = '" + pesquisa + "') ";
//            } else {
//                sql = "SELECT VendCod FROM vendas WHERE VendFun IN (SELECT FunCod FROM Funcionario WHERE " + campoPesquisa + " = '" + pesquisa + "' )";
//            }
//
//        }
        switch (numeroTabela) {
            case 1:
                sql = "SELECT vendas.VendCod, vendas.VendQuant, vendas.VendPreco, vendas.VendFun, vendas.VendProd, vendas.VendFun, vendas.VendProd"
                        + " FROM WHERE vendas.VendCod =" + pesquisa;
                break;
            case 2:
                sql = "SELECT vendas.VendCod, vendas.VendQuant, vendas.VendPreco, vendas.VendFun, vendas.VendProd, vendas.VendFun, vendas.VendProd"
                        + " FROM WHERE vendas.VendQuant =" + pesquisa;
                break;
            case 3:
                sql = "SELECT vendas.VendCod, vendas.VendQuant, vendas.VendPreco, vendas.VendFun, vendas.VendProd, vendas.VendFun, vendas.VendProd"
                        + " FROM WHERE vendas.VendPreco =" + pesquisa;
                break;
            case 4:
                sql = "SELECT vendas.VendCod, vendas.VendQuant, vendas.VendPreco, vendas.VendFun, vendas.VendProd, vendas.VendFun, vendas.VendProd"
                        + " FROM WHERE vendas.VendProd ='" + pesquisa + "'";
                break;
            case 5:
                sql = "SELECT vendas.VendCod, vendas.VendQuant, vendas.VendPreco, vendas.VendFun, vendas.VendProd, vendas.VendFun, vendas.VendProd"
                        + " FROM WHERE vendas.VendFun ='" + pesquisa + "'";
                break;
            default:
                sql = null;
        }

        //Fase 3
//        if (conecta.getCon()) {
//            try {
//                stm = conecta.con.prepareStatement(sql);
//                rs = stm.executeQuery();
//
//                if (!rs.wasNull()) {
//                    while (rs.next()) {
//                        CodigosVenda.add(String.valueOf(rs.getInt("VendCod")));
//                    }
//                } else {
//                    DadosRetornados = false;
//                }
//
//            } catch (SQLException ex) {
//                Logger.getLogger(BuscarVendas.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
        //Fase 4 INNER JOIN!
        if (DadosRetornados != false) {
//            for (String codVenda : CodigosVenda) {
//                sql = "SELECT vendas.VendCod, vendas.VendQuant, vendas.VendPreco, vendas.VendFun, vendas.VendProd, funcionario.FunNome, produto.ProNome"
//                        + " FROM vendas, funcionario, produto WHERE vendas.VendCod =" + codVenda + " AND vendas.VendProd = produto.ProCod AND vendas.VendFun = funcionario.FunCod";
            if (!pesquisa.equals("")) {
                if (conecta.getCon()) {
                    try {
                        stm = conecta.con.prepareStatement(sql);
                        rs = stm.executeQuery();

                        while (rs.next()) {
                            //        VendCod
//VendQuant
//VendPreco
//ProNome
//FunNome
                            tabela.addRow(new String[]{rs.getString("VendCod"), rs.getString("VendProd"), rs.getString("VendQuant"),
                                rs.getString("VendPreco"), rs.getString("VendFun")});
                        }
                        conecta.fechar();

                    } catch (SQLException err) {
                        Logger.getLogger(BuscarVendas.class.getName()).log(Level.SEVERE, null, err);

                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Nenhum resultado foi encontrado");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            }
        }
    }//GEN-LAST:event_jToggleButtonPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxCampoPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVenda;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButtonPesquisar;
    // End of variables declaration//GEN-END:variables
}
